# Generated by Django 5.2 on 2025-07-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0006_add_zones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'staff_member__name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['name']},
        ),
    ]
