# Generated by Django 5.2 on 2025-08-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0008_add_user_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={},
        ),
        migrations.AddField(
            model_name='staffmember',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
    ]
