# Generated by Django 5.2 on 2025-08-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0009_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='chantier_at_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_attendance.city', verbose_name='Chantier au moment de la présence'),
        ),
    ]
