# Generated by Django 5.2 on 2025-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'absence"),
        ),
    ]
